# inherit from global/pipelines
from: deploy-to-nonprod.yaml

# overrides
trigger:
  name: hourly
  type: cron
  enabled: false
  expr: 0 0 * * *
  tz: America/Chicago
  build: 0.1.8

notifications:
  enabled: false
