stages:

  - name: deploy
    steps:
      - name: deploy-to-int
        command:
          type: deploy
          stack: int
          timeout: 120
      - name: deploy-to-stg
        command:
          type: deploy
          stack: stg
          timeout: 120

  - name: deploy-again
    steps:
      - name: deploy-to-int
        command:
          type: deploy
          stack: int
          timeout: 120
      - name: deploy-to-stg
        command:
          type: deploy
          stack: stg
          timeout: 120

notifications:
  enabled: true
  events: started,finished
  channels: devops
