image:
  provider: dockerhub1
  regex: .*

stages:

  - name: canary-choice
    steps:
      - name: canary-choice
        command:
          type: choice
          message: Deploy canary?
          choices:
            - yes
            - no
          timeout: 600

  - name: deploy-canary
    order: 10
    steps:
      - name: deploy-canary
        condition:
          type: choice
          stage: canary-choice
          step: canary-choice
          value: yes
        command:
          type: deploy-canary
          stack: dev
          replicas: 1
          timeout: 120

  - name: deploy-choice
    steps:
      - name: deploy-choice
        command:
          type: choice
          message: Deploy new build?
          choices:
            - yes
            - no
          timeout: 600

  - name: undeploy-canary
    order: 10
    steps:
      - name: undeploy-canary
        condition:
          type: choice
          stage: canary-choice
          step: canary-choice
          value: yes
        command:
          type: undeploy-canary
          stack: dev
          timeout: 120

  - name: deploy-dev
    order: 10
    steps:
      - name: deploy-dev
        condition:
          type: choice
          stage: deploy-choice
          step: deploy-choice
          value: yes
        command:
          type: deploy
          stack: dev
          replicas: 1
          timeout: 120
