stages:
  - name: choice-int
    steps:
      - name: choice-int
        command:
          type: choice
          message: Deploy to int?
          choices:
            - yes
            - no
          timeout: 3600

  - name: deploy-to-int
    steps:
      - name: deploy-to-int
        condition:
          type: choice
          stage: choice-int
          step: choice-int
          value: yes
        command:
          type: deploy
          stack: int
          timeout: 120

  - name: choice-stg
    steps:
      - name: choice-stg
        command:
          type: choice
          message: Deploy to stg?
          choices:
            - yes
            - no
          timeout: 3600
          
  - name: deploy-to-stg
    steps:
      - name: deploy-to-stg
        condition:
          type: choice
          stage: choice-stg
          step: choice-stg
          value: yes
        command:
          type: deploy
          stack: stg
          timeout: 120

notifications:
  enabled: false
  events: started,blocked,finished
  channels: devops
