image:
  provider: dockerhub1

stages:

  - name: deploy
    steps:
      - name: deploy-to-dev
        command:
          type: deploy
          stack: dev
          timeout: 120

notifications:
  enabled: false
  events: started,finished
  provider: slack1
  channels: devops
