# stages are executed sequentially, all steps in a stage are executed in parallel

image:
  regex: .*

stages:

  - name: approve
    order: 10
    steps:
      - name: approve-pipeline
        command:
          type: approve
          timeout: 3600

  - name: deploy
    order: 20
    steps:
      - name: deploy-to-dev
        command:
          type: deploy
          stack: dev
          timeout: 120

  - name: deploy-in-parallel
    order: 20
    steps:
      - name: deploy-in-parallel
        command:
          type: deploy
          stack: dev
          timeout: 120

notifications:
  enabled: false
  events: started,finished
  channels: devops
