# stages are executed sequentially, all steps in a stage are executed in parallel

image:
  provider: dockerhub1
  regex: .*

stages:

  - name: deploy
    order: 10
    steps:
      - name: deploy-to-dev
        command:
          type: deploy
          stack: dev
          timeout: 120

notifications:
  enabled: false
  events: started,finished
  provider: slack1
  channels: devops
