stages:

  - name: deploy
    steps:
      - name: deploy-to-int
        command:
          type: deploy
          stack: int
          timeout: 120

notifications:
  enabled: false
  events: started,finished
  provider: slack
  channels: devops
  
